M48
; DRILL file {KiCad (6.0.2)} date Sat Dec 31 16:06:55 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-31T16:06:55+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1772
%
G90
G05
T1
X2.1654Y-3.9961
T2
X2.8543Y-2.5394
X2.8543Y-5.0984
X4.311Y-2.5394
X4.311Y-5.0984
T0
M30
